const ROLE_CODES = {
  ADMIN: 'ADMIN',
  STAFF: 'STAFF',
  DIRECTOR: 'DIRECTOR',
  PRODUCER: 'PRODUCER',
  CAMERAMAN: 'CAMERAMAN',
  TRANSMISSION: 'TRANSMISSION',
  EDITOR: 'EDITOR',
  DRIVER: 'DRIVER'
}

const PUNCH_MODEL = {
  TWO: 'TWO',
  FOUR: 'FOUR'
}

const PUNCH_STATUS = {
  NORMAL: 'NORMAL',
  LATE: 'LATE',
  MISSING: 'MISSING'
}

const ABSENCE_TYPE = {
  LEAVE: 'LEAVE',
  BUSINESS_TRIP: 'BUSINESS_TRIP'
}

const ABSENCE_STATUS = {
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  PENDING: 'PENDING'
}

module.exports = {
  ROLE_CODES,
  PUNCH_MODEL,
  PUNCH_STATUS,
  ABSENCE_TYPE,
  ABSENCE_STATUS
}
