module.exports = {
  UNAUTHORIZED: 'UNAUTHORIZED',
  FORBIDDEN: 'FORBIDDEN',
  INVALID_INPUT: 'INVALID_INPUT',
  NOT_FOUND: 'NOT_FOUND',
  DUPLICATE_PUNCH: 'DUPLICATE_PUNCH',
  OUTSIDE_FENCE: 'OUTSIDE_FENCE',
  INTERNAL_ERROR: 'INTERNAL_ERROR'
}
